"""empty message

Revision ID: cc276b828c22
Revises: 7739ab8bb8d7
Create Date: 2023-01-26 20:25:35.083109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc276b828c22'
down_revision = '7739ab8bb8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_foreign_key('characters_id_fkey', 'favorites', ['id'], ['id'])

    # ### end Alembic commands ###
